#!/bin/sh

#set -x

ODROID_STAMPER_DIR="/usr/share/odroid-stamper"

#TOPDIR=${ODROID_STAMPER_CHECKOUT:-${ODROID_STAMPER_DIR}}
TOPDIR=$PWD

DEFAULT_CONFIG=${TOPDIR}/.config

download_dir="/var/cache/odroid-stamper/downloads"
out_dir=${PWD}

. ${TOPDIR}/menu
. ${TOPDIR}/default
. ${TOPDIR}/functions

if [ ! -f ${DEFAULT_CONFIG} ]; then
    default_config ${DEFAULT_CONFIG}
fi

. ${DEFAULT_CONFIG}

do_menu

[ -f ${TOPDIR}/configs/${DISTRO}-${FLAVOUR} ] && \
	. ${TOPDIR}/configs/${DISTRO}-${FLAVOUR}
. ${TOPDIR}/boards/${BOARD}/functions

trap "trap_ctrlc" 2
trap "cleanup" 0
trap "panic" 1 3 15

do_custom_installer ${download_dir} ${out_dir}

# vim: set ft=sh ts=4 sw=4 expandtab
