#!/bin/sh

#set -x

[ -z "$1" ] || CUSTOMOS=${1}

ODROID_STAMPER_DIR="/usr/share/odroid-stamper"

TOPDIR=${ODROID_STAMPER_CHECKOUT:-${ODROID_STAMPER_DIR}}
WORKDIR=$PWD
RUN_MENU=true

DEFAULT_CONFIG=${WORKDIR}/.config

download_dir="/var/cache/odroid-stamper/downloads"
out_dir=${WORKDIR}

. ${TOPDIR}/menu
. ${TOPDIR}/default
. ${TOPDIR}/functions

if [ -f ${TOPDIR}/custom/${CUSTOMOS}/config ]; then
	cp -f ${TOPDIR}/custom/${CUSTOMOS}/config ${DEFAULT_CONFIG} || exit 1
	RUN_MENU=false
fi

if [ ! -f ${DEFAULT_CONFIG} ]; then
    default_config ${DEFAULT_CONFIG}
fi

. ${DEFAULT_CONFIG}

[ "${RUN_MENU}" = "true" ] && do_menu

[ "x${IMAGE_FILE}" = "x" ] && IMAGE_FILE=$(image_file ${DISTRO} ${FLAVOUR} ${BOARD})
OUTFILE=${out_dir}/${IMAGE_FILE}

[ -f ${TOPDIR}/configs/${DISTRO}-${FLAVOUR} ] && \
	. ${TOPDIR}/configs/${DISTRO}-${FLAVOUR}
. ${TOPDIR}/boards/${BOARD}/functions

trap "trap_ctrlc" 2
trap "cleanup" 0
trap "panic" 1 3 15

[ "x${TARGET_DEVCIE}" = "x" ] && TARGET_DEVICE=${out_dir}/binary.img

do_custom_installer ${download_dir} ${out_dir}

# vim: set ft=sh ts=4 sw=4 expandtab
