#!/bin/sh

PACKAGE=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/awesometic/odroid-etcher/releases | grep download_url | grep arm64 | sort -rV | head -1 | awk '{print $2}' | tr -d '"')

wget ${PACKAGE} -O /tmp/odroid-etcher.deb
dpkg -i /tmp/odroid-etcher.deb || true
apt install -y --no-install-recommends --fix-broken

chmod 644 /etc/systemd/system/odroid-etcher.service
systemctl enable odroid-etcher
