#!/bin/sh

CODENAME=$(lsb_release -cs)

[ "x${CODENAME}" = "xfocal" ] || OPTION="[trusted=yes]"

cat>>/etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list<<__EOF
deb ${OPTION} http://ppa.linuxfactory.or.kr @@DEFAULT_DISTRO@@ rk3568
deb ${OPTION} http://ppa.linuxfactory.or.kr @@DEFAULT_DISTRO@@ rockchip
__EOF

sed -i "/non-free/d" /etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list
sed -i "/contrib/d" /etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list
