#!/bin/sh

cat>>/etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list<<__EOF
deb [trusted=yes] http://ppa.linuxfactory.or.kr @@DEFAULT_DISTRO@@ rk3568
deb [trusted=yes] http://ppa.linuxfactory.or.kr @@DEFAULT_DISTRO@@ rockchip
__EOF

sed -i "/non-free/d" /etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list
sed -i "/contrib/d" /etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list
