#!/bin/sh

CODENAME=$(cat /etc/os-release | grep VERSION_CODENAME | cut -d'=' -f2)

case ${CODENAME} in
	"focal" | "buster")
		OPTION=""
		;;
	*)
		OPTION="[trusted=yes]"
		;;
esac

cat>/etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list<<__EOF
deb ${OPTION} http://ppa.linuxfactory.or.kr @@DEFAULT_DISTRO@@ main
deb ${OPTION} http://ppa.linuxfactory.or.kr @@DEFAULT_DISTRO@@ rk3568
deb ${OPTION} http://ppa.linuxfactory.or.kr @@DEFAULT_DISTRO@@ rockchip
__EOF
