#!/bin/sh

INTERNAL-APT=/etc/apt/sources.list.d/ppa-linuxfactory-or-kr.list

if [ -f ${INTERNAL_APT} ]; then
	sed -i "/internal/d" ${INTERNAL_APT}
fi

cat>>${INTERNAL_APT}<<__EOF
deb http://ppa.linuxfactory.or.kr focal internal
__EOF
