#!/bin/sh

rm -f /etc/apt/sources.list.d/launchpad-hardkernel-ppa.list

apt update && apt upgrade -y
apt install -y \
	odroid-base \
	@@DEFAULT_FLAVOUR_PACKAGES@@ \
	@@DEFAULT_KERNEL_PACKAGE@@ \
	@@DEFAULT_BOOTSCRIPT_PACKAGE@@
