#!/bin/sh

export DEBIAN_FRONTEND=noninteractive

locale-gen en_US.UTF-8

rm -f /etc/apt/sources.list.d/launchpad-hardkernel-ppa.list

apt update && apt upgrade -y
apt install @@DEFAULT_APT_OPTIONS@@ \
	odroid-base \
	rsync \
	@@DEFAULT_FLAVOUR_PACKAGES@@ \
	@@DEFAULT_KERNEL_PACKAGE@@ \
	@@DEFAULT_BOOTSCRIPT_PACKAGE@@
