#!/bin/sh

echo "I: create default user account"
adduser --gecos @@DEFAULT_USER@@ --disabled-login @@DEFAULT_USER@@

echo "I: set default user password"
echo "@@DEFAULT_USER@@:@@DEFAULT_USER_PASSWD@@" | chpasswd

if @@ALLOW_ROOT_LOGIN@@; then
	echo "I: add user '@@DEFAULT_USER@@' to group 'sudo'"
	adduser @@DEFAULT_USER@@ sudo
fi

echo "I: set default groups for a defaule user"
adduser @@DEFAULT_USER@@ audio
adduser @@DEFAULT_USER@@ video
