#!/bin/sh

sed -i "/ \/boot /d" /etc/fstab
sed -i "/ \/ /d" /etc/fstab

if [ "x@@DEFAULT_DEV_ROOTFS@@" != "x" ]; then
	cat <<__EOF | tee -a /etc/fstab >/dev/null
UUID="@@DEFAULT_DEV_ROOTFS@@" /     ext4 rw,relatime,data=ordered 0 0
__EOF
fi

if [ "x@@DEFAULT_DEV_BOOT@@" != "x" ]; then
	cat <<__EOF | tee -a /etc/fstab >/dev/null
UUID="@@DEFAULT_DEV_BOOT@@" /boot ext2 rw,relatime,errors=continue 0 0
__EOF
fi
