#!/bin/sh

PLYMOUTH_CMDLINE="plymouth.ignore-serial-consoles"

if [ -f /etc/default/flash-kernel ]; then
	. /etc/default/flash-kernel

	sed -i "s/^LINUX_KERNEL_CMDLINE=.*/LINUX_KERNEL_CMDLINE=\"root=UUID=@@DEFAULT_DEV_ROOTFS@@ $LINUX_KERNEL_CMDLINE\"/g" \
		/etc/default/flash-kernel
fi

if dpkg -s plymouth >/dev/null; then
	echo "FRAMEBUFFER=y" > /etc/initramfs-tools/conf.d/splash

	if [ -f /etc/default/flash-kernel ]; then
		. /etc/default/flash-kernel

		sed -i "s/^LINUX_KERNEL_CMDLINE=.*/LINUX_KERNEL_CMDLINE=\"$LINUX_KERNEL_CMDLINE $PLYMOUTH_CMDLINE\"/g" \
			/etc/default/flash-kernel
	fi
fi

echo flash-kernel flash-kernel/linux_cmdline string @@LINUX_KERNEL_CMDLINE@@  | \
	     debconf-set-selections

if [ "x@@LIVESYSTEM@@" = "xtrue" ]; then
	if [ -f /etc/default/flash-kernel ]; then
		. /etc/default/flash-kernel

		sed -i "s/^LINUX_KERNEL_CMDLINE=.*/LINUX_KERNEL_CMDLINE=\"$LINUX_KERNEL_CMDLINE boot=casper toram\"/g" \
			/etc/default/flash-kernel
	fi
fi

/usr/sbin/update-initramfs -u
rm -rf /overlay
