#!/bin/sh

if [ -f /etc/fstab ]; then
	# Remove BOOT/ROOTFS mount points
	sed -i "/ \/boot /d" /etc/fstab
	sed -i "/ \/ /d" /etc/fstab
	# Remove EFI partition not to mount
	sed -i "/\/boot\/efi/d" /etc/fstab

	# Remove yet another root mount point via 'cloud-img-root'
	sed -i "/cloudimg-rootfs/d" /etc/fstab
fi

if [ "x@@DEFAULT_DEV_ROOTFS@@" != "x" ]; then
	cat <<__EOF | tee -a /etc/fstab >/dev/null
UUID="@@DEFAULT_DEV_ROOTFS@@" /     ext4 rw,relatime,data=ordered 0 0
__EOF
fi

if [ "x@@DEFAULT_DEV_BOOT@@" != "x" ]; then
	cat <<__EOF | tee -a /etc/fstab >/dev/null
UUID="@@DEFAULT_DEV_BOOT@@" /boot ext2 rw,relatime,errors=continue 0 0
__EOF
fi

# Temporary create UUID of root file system since 'flash-kernel' checks it
# to add 'root=UUID...' to initramfs.
touch /dev/disk/by-uuid/@@DEFAULT_DEV_ROOTFS@@

update-initramfs -u
