#!/bin/sh

echo flash-kernel flash-kernel/linux_cmdline string @@LINUX_KERNEL_CMDLINE@@  | \
	     debconf-set-selections

if [ "x@@LIVESYSTEM@@" = "xtrue" ]; then
	if [ -f /etc/default/flash-kernel ]; then
		. /etc/default/flash-kernel

		sed -i "s/^LINUX_KERNEL_CMDLINE=.*/LINUX_KERNEL_CMDLINE=\"$LINUX_KERNEL_CMDLINE boot=casper toram\"/g" \
			/etc/default/flash-kernel
	fi
fi

/usr/sbin/update-initramfs -u
rm -rf /overlay
