#!/bin/sh

echo flash-kernel flash-kernel/linux_cmdline string @@LINUX_KERNEL_CMDLINE@@  | \
	     debconf-set-selections

if [ "x@@LIVESYSTEM@@" = "xtrue" ]; then
	cat>/usr/share/flash-kernel/preboot.d/upstream/99-liveboot<<__EOF
setenv bootargs "\${bootargs} boot=casper toram"
__EOF
fi

/usr/sbin/flash-kernel
