#!/bin/sh

truncate -s 0 /etc/machine-id

rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl

apt autoremove -y
apt clean

rm -f /etc/flash-kernel/machine
rm -f /etc/apt/apt.conf.d/99debconf

rm -rf /tmp/*
rm -rf ~/.bash_history
rm -rf /root/default

chown -R root:root /boot
chown -R root:root /etc
chown -R root:root /root
